"""MMS Config Writer — rewrites MMS ini files based on Anarchy Radio FM toggle states.

On startup and when toggles change, this module regenerates the three MMS
config files in the GAME'S user config directory:
  C:\\Users\\<user>\\...\\my games\\XCOM2 War of the Chosen\\XComGame\\Config\\

NOT the mod folder — Steam Workshop overwrites that on updates.

A state is silenced only when Anarchy Radio FM can actually cover it — the
toggle is on AND the folder has something to play. Otherwise no entry is
written and the fallback chain takes over: MMS plays whatever music pack the
user has installed, and failing that its own settings hand back to the stock
soundtrack. Silencing a state we have no music for is the one outcome nobody
wants, because it produces dead air rather than a fallback.

Changes take effect on the NEXT game launch (ini is read once at startup).
"""

import os
import console


# Set by sync_ini_files() from xipod_config.json's game_config_folder.
_config_dir = None

_SILENCE = "XiPod_Silence.silent_Cue"


def _reason(toggle_key, toggles, has_tracks):
    """Why a state isn't being silenced, or None if it is.

    Kept as prose because it goes straight into the generated ini, where it
    is the only explanation a user gets for why a screen still has MMS music.
    """
    if not toggles.get(toggle_key, True):
        return "toggled off"
    if has_tracks is not None and not has_tracks.get(toggle_key, True):
        return "no tracks in its folder"
    return None


# ------------------------------------------------------------------ #
#  Shell config
# ------------------------------------------------------------------ #

def _build_shell_ini(skip_reason, pack_defs=None):
    """Generate XComShellSound.ini content."""
    lines = [
        "[MusicModdingSystem.MMS_UISL_UIShell]",
        "; Anarchy Radio FM: Replace MMS shell music with silence.",
        "; ShellCues take priority over FallbackCues.",
        "; Auto-generated by Anarchy Radio FM — do not edit manually.",
    ]
    if skip_reason:
        lines.append(f"; SHELL {skip_reason} — MMS plays its own shell music.")
        return "\n".join(lines) + "\n"

    lines.append(f'+ShellCues="{_SILENCE}"')

    # A music pack that adds its own +ShellCues sits in the same non-fallback
    # bucket as ours, and MMS_UISL_UIShell shuffles before sorting, so the
    # menu becomes a coin flip. There is no MusicID to register here — the
    # shell autogenerates its ids — so the only lever is which ARRAY the cue
    # is in: FallbackCues is skipped outright while bAllowFallback is off.
    # Moving it there keeps the pack's menu music available (it plays again
    # the moment the shell toggle goes off, or if the user allows fallbacks)
    # without letting it contend for a screen we're covering.
    cues = (pack_defs or {}).get("shell_menu") or []
    if cues:
        lines.append("")
        lines.append("; Pack menu cues moved to the fallback bucket for this state.")
        for cue in cues:
            lines.append(f'-ShellCues="{cue}"')
            lines.append(f'+FallbackCues="{cue}"')

    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ #
#  Strategy config
# ------------------------------------------------------------------ #

# Toggleable strategy entries: (toggle_key, [(MusicID, Group, has_fade_flags)])
_TOGGLEABLE_STRATEGY = [
    ("avenger", [
        ("XiPod_Silence_HQ",  "eSSG_Chapter01", True),
        ("XiPod_Silence_HQ2", "eSSG_Chapter02", True),
        ("XiPod_Silence_HQ3", "eSSG_Chapter03", True),
    ]),
    ("geoscape", [
        ("XiPod_Silence_Geoscape", "eSSG_Geoscape", False),
    ]),
    ("squadselect", [
        ("XiPod_Silence_SquadSelect", "eSSG_SquadSelect", True),
    ]),
    ("victory", [
        ("XiPod_Silence_AAFlawless",   "eSSG_AfterActionFlawless",   False),
        ("XiPod_Silence_AACasualties", "eSSG_AfterActionCasualties", False),
    ]),
    ("defeat", [
        ("XiPod_Silence_AALoss", "eSSG_AfterActionLoss", False),
        ("XiPod_Silence_Loss",   "eSSG_Loss",            False),
    ]),
]


def _strategy_entry(music_id, group, has_fade):
    """Build one +MusicDefs=(...) block matching the user's ini format."""
    if has_fade:
        return (
            f'+MusicDefs=(MusicID="{music_id}", \\\\\n'
            f'            CuePath="{_SILENCE}", \\\\\n'
            f'            dontFadeIn=true, \\\\\n'
            f'            dontFadeOut=true, \\\\\n'
            f'            Group={group})'
        )
    else:
        return (
            f'+MusicDefs=(MusicID="{music_id}", \\\\\n'
            f'            CuePath="{_SILENCE}", \\\\\n'
            f'            Group={group})'
        )


def _fallback_lines(key, pack_defs, array_name, skip_reason):
    """Register another pack's definitions as fallbacks for one state.

    MMS decides between equally-eligible definitions with Rand(), so a music
    pack and our silence cue on the same screen is a coin flip that lands
    differently each session. Its own stock music avoids that by being listed
    as a fallback; doing the same to a pack's definitions, only for the states
    we're actually covering, reduces the draw to a single candidate.

    Skipped when we aren't covering the state — the pack should own that
    screen outright, which is the entire point of running the two together.
    """
    ids = (pack_defs or {}).get(key) or []
    if not ids:
        return []
    if skip_reason:
        return [f";  ({len(ids)} pack def(s) left active — {key} is {skip_reason})"]

    out = [f"; {key}: yielding these pack defs to Anarchy Radio FM for this state."]
    out.extend(f'+{array_name}="{i}"' for i in ids)
    return out


def _build_strategy_ini(toggles, has_tracks=None, pack_defs=None):
    """Generate XComStrategySound.ini content."""
    lines = [
        "[MusicModdingSystem.MMS_XComStrategySoundManager]",
        "; Anarchy Radio FM: Replace MMS strategy music with silence for enabled states.",
        "; Auto-generated by Anarchy Radio FM — do not edit manually.",
        "",
    ]

    # Toggleable entries
    for toggle_key, entries in _TOGGLEABLE_STRATEGY:
        skip_reason = _reason(toggle_key, toggles, has_tracks)
        if not skip_reason:
            for music_id, group, has_fade in entries:
                lines.append(_strategy_entry(music_id, group, has_fade))
                lines.append("")
        else:
            lines.append(f"; {toggle_key.upper()} {skip_reason} — MMS plays its own music.")
            for music_id, group, _ in entries:
                lines.append(f";  (skipped: {music_id} / {group})")
            lines.append("")

        fb = _fallback_lines(toggle_key, pack_defs, "FallbackSongs", skip_reason)
        if fb:
            lines.extend(fb)
            lines.append("")

    # Credits — always commented out
    lines.append(";+MusicDefs=(MusicID=\"XiPod_Silence_Credits\", \\\\")
    lines.append(";            CuePath=\"XiPod_Silence.silent_Cue\", \\\\")
    lines.append(";            dontFadeIn=true, \\\\")
    lines.append(";            dontFadeOut=true, \\\\")
    lines.append(";            Group=eSSG_Credits)")
    lines.append("")

    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ #
#  Tactical config
# ------------------------------------------------------------------ #

def _build_tactical_ini(skip_reason, pack_defs=None):
    """Generate XComTacticalSound.ini content."""
    lines = [
        "[MusicModdingSystem.MMS_XComTacticalSoundManager]",
        "; Anarchy Radio FM: Replace MMS tactical music with silence.",
        "; The wildcards below make these outscore MMS's stock defs. Being",
        "; non-fallback is NOT enough on the tactical side — MMS re-sorts by",
        "; score afterwards and the tie-break is random. See mms_config.py.",
        "; Auto-generated by Anarchy Radio FM — do not edit manually.",
        "",
    ]
    if not skip_reason:
        # NOTE: UE3 ini line continuation is a double backslash (\\),
        # matching the MMS reference configs. A single backslash breaks
        # the CombatDefs/ExploreDefs parse and MMS plays its own music.
        #
        # The wildcards are not decoration — they are what makes the
        # silencing deterministic. MMS picks a tactical set like this:
        #
        #     ShuffleTSets(InSets);                  // random order
        #     if (!bAllowFallback) Sort(ByFallback); // stock music last
        #     Sort(SortMissionSets);                 // by score
        #     return InSets[0];
        #
        # MMS does register all 43 of its own defs as FallbackDefs, so the
        # second line should push them behind ours. But the score sort runs
        # afterwards, every def with unset fields scores the same 1186, and
        # UE3's Sort is not stable — so sorting that field of ties throws the
        # fallback ordering away and the winner comes back down to the
        # shuffle. That is a coin flip per mission, and it is the real reason
        # for "MMS silences most of the soundtrack but not all of it".
        #
        # Score is a bitfield: mission wildcard 2048, plot wildcard 256,
        # biome wildcard 32, rain eRR_Always 2 — total 2338 against the 1186
        # of every stock def, which cannot reach the wildcard branches
        # because its fields are empty. Winning on score settles it before
        # the tie-break is ever consulted.
        # NOTE: no rain= inside EnvReq. An earlier version wrote
        # rain=eRR_Always and the whole entry stopped parsing — the def
        # vanished from MMS's pool entirely, which reads exactly like losing
        # the draw (no XiPod def in any "found ... with a score of" line,
        # while a pack scoring lower than us kept winning). Nothing else in
        # MMS's own configs or in any pack writes an enum inside a nested
        # struct here. The struct already declares
        # structdefaultproperties { rain = eRR_Always }, so the +2 arrives
        # anyway and the total is still 2338.
        lines.append(
            f'+CombatDefs=(ID="XiPod_Silence_Combat", \\\\\n'
            f'             MissionMusicSet="wildcard", \\\\\n'
            f'             EnvReq=(biome="wildcard", plot="wildcard"), \\\\\n'
            f'             XLoopCue="{_SILENCE}")'
        )
        lines.append("")
        lines.append(
            f'+ExploreDefs=(ID="XiPod_Silence_Explore", \\\\\n'
            f'              MissionMusicSet="wildcard", \\\\\n'
            f'              EnvReq=(biome="wildcard", plot="wildcard"), \\\\\n'
            f'              Cue="{_SILENCE}")'
        )
    else:
        lines.append(f"; BATTLE {skip_reason} — MMS plays its own tactical music.")
        lines.append(f';+CombatDefs=(ID="XiPod_Silence_Combat", XLoopCue="{_SILENCE}")')
        lines.append(f';+ExploreDefs=(ID="XiPod_Silence_Explore", Cue="{_SILENCE}")')
    lines.append("")

    # Belt and braces on top of winning the score: a pack that also sets
    # wildcards would tie with us, and a tie goes back to MMS's shuffle.
    fb = _fallback_lines("battle", pack_defs, "FallbackDefs", skip_reason)
    if fb:
        lines.extend(fb)
        lines.append("")

    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ #
#  Public API
# ------------------------------------------------------------------ #

def sync_ini_files(toggles, config_folder=None, has_tracks=None, pack_defs=None,
                   mod_config_dirs=None):
    """Rewrite all three MMS config files based on current toggle states.

    Args:
        toggles: dict mapping toggle keys to bool, e.g.
                 {"shell_menu": True, "avenger": True, "battle": False, ...}
        config_folder: path to the game's user Config directory.
                       Only needed on first call; cached after that.
        has_tracks: dict mapping the same toggle keys to whether that state
                    resolves to any playable audio. A state with none is left
                    unsilenced so MMS can cover it — see the module docstring.
                    Omit to silence purely on toggles.
        pack_defs: {toggle key: [definition ids]} for enabled third-party MMS
                   music packs, from mms_packs.find_pack_defs(). Their
                   definitions are registered as fallbacks on the states we
                   cover, so MMS stops choosing between them and us at random.
    """
    global _config_dir

    if config_folder:
        _config_dir = config_folder

    if not _config_dir:
        console.warn("MMS config: no config directory set (need log_path on first call).")
        return

    if not os.path.isdir(_config_dir):
        console.warn(f"MMS config dir not found: {_config_dir}")
        return

    changes = []

    # Shell
    shell_path = os.path.join(_config_dir, "XComShellSound.ini")
    shell_content = _build_shell_ini(_reason("shell_menu", toggles, has_tracks),
                                     pack_defs)
    if _write_if_changed(shell_path, shell_content):
        changes.append("shell")

    # Strategy
    strat_path = os.path.join(_config_dir, "XComStrategySound.ini")
    strat_content = _build_strategy_ini(toggles, has_tracks, pack_defs)
    if _write_if_changed(strat_path, strat_content):
        changes.append("strategy")

    # Tactical
    tact_path = os.path.join(_config_dir, "XComTacticalSound.ini")
    tact_content = _build_tactical_ini(_reason("battle", toggles, has_tracks),
                                       pack_defs)
    if _write_if_changed(tact_path, tact_content):
        changes.append("tactical")

    # The copies that actually get read. MMS loads config from each mod's own
    # Config folder; the game never mirrors mod config files into the user's
    # Documents config directory, so the writes above are kept only because
    # they are harmless and long-standing. Everything downstream of MMS
    # depends on these.
    written_to_mod = 0
    for mod_dir in (mod_config_dirs or []):
        if not os.path.isdir(mod_dir):
            continue
        _write_if_changed(os.path.join(mod_dir, "XComShellSound.ini"), shell_content)
        _write_if_changed(os.path.join(mod_dir, "XComStrategySound.ini"), strat_content)
        _write_if_changed(os.path.join(mod_dir, "XComTacticalSound.ini"), tact_content)
        written_to_mod += 1

    if not written_to_mod:
        # Loud, because the failure is otherwise invisible: the app plays its
        # music perfectly and the game plays straight over the top of it.
        console.error("Can't find the installed Anarchy Radio FM mod folder — "
                      "the game's own music will NOT be silenced.")
        console.shen("Set \"workshop_folder\" in xipod_config.json (or "
                     "\"mod_config_folder\" for a non-Workshop install), "
                     "then restart me.")

    if changes:
        console.signal(f"MMS config updated: {', '.join(changes)} — takes effect on next game launch.")
    else:
        console.debug("MMS config: no changes needed.")


def _write_if_changed(path, content):
    """Write file only if content differs. Returns True if written."""
    try:
        if os.path.exists(path):
            with open(path, 'r', encoding='utf-8') as f:
                existing = f.read()
            if existing == content:
                return False
    except Exception:
        pass  # If we can't read, just write

    try:
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    except Exception as e:
        console.warn(f"Failed to write {path}: {e}")
        return False
