"""MMS Config Writer — rewrites MMS ini files based on Anarchy Radio FM toggle states.

On startup and when toggles change, this module regenerates the three MMS
config files in the GAME'S user config directory:
  C:\\Users\\<user>\\...\\my games\\XCOM2 War of the Chosen\\XComGame\\Config\\

NOT the mod folder — Steam Workshop overwrites that on updates.

States with Anarchy Radio FM ENABLED get a silent SoundCue entry that suppresses MMS.
States with Anarchy Radio FM DISABLED get no entry — MMS plays its own music.

Changes take effect on the NEXT game launch (ini is read once at startup).
"""

import os
import console


# Set by sync_ini_files() from xipod_config.json's game_config_folder.
_config_dir = None

_SILENCE = "XiPod_Silence.silent_Cue"


# ------------------------------------------------------------------ #
#  Shell config
# ------------------------------------------------------------------ #

def _build_shell_ini(enabled):
    """Generate XComShellSound.ini content."""
    lines = [
        "[MusicModdingSystem.MMS_UISL_UIShell]",
        "; Anarchy Radio FM: Replace MMS shell music with silence.",
        "; ShellCues take priority over FallbackCues.",
        "; Auto-generated by Anarchy Radio FM — do not edit manually.",
    ]
    if enabled:
        lines.append(f'+ShellCues="{_SILENCE}"')
    else:
        lines.append("; Anarchy Radio FM shell music DISABLED — MMS plays its own shell music.")
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ #
#  Strategy config
# ------------------------------------------------------------------ #

# Toggleable strategy entries: (toggle_key, [(MusicID, Group, has_fade_flags)])
_TOGGLEABLE_STRATEGY = [
    ("avenger", [
        ("XiPod_Silence_HQ",  "eSSG_Chapter01", True),
        ("XiPod_Silence_HQ2", "eSSG_Chapter02", True),
        ("XiPod_Silence_HQ3", "eSSG_Chapter03", True),
    ]),
    ("geoscape", [
        ("XiPod_Silence_Geoscape", "eSSG_Geoscape", False),
    ]),
    ("squadselect", [
        ("XiPod_Silence_SquadSelect", "eSSG_SquadSelect", True),
    ]),
    ("victory", [
        ("XiPod_Silence_AAFlawless",   "eSSG_AfterActionFlawless",   False),
        ("XiPod_Silence_AACasualties", "eSSG_AfterActionCasualties", False),
    ]),
    ("defeat", [
        ("XiPod_Silence_AALoss", "eSSG_AfterActionLoss", False),
        ("XiPod_Silence_Loss",   "eSSG_Loss",            False),
    ]),
]


def _strategy_entry(music_id, group, has_fade):
    """Build one +MusicDefs=(...) block matching the user's ini format."""
    if has_fade:
        return (
            f'+MusicDefs=(MusicID="{music_id}", \\\\\n'
            f'            CuePath="{_SILENCE}", \\\\\n'
            f'            dontFadeIn=true, \\\\\n'
            f'            dontFadeOut=true, \\\\\n'
            f'            Group={group})'
        )
    else:
        return (
            f'+MusicDefs=(MusicID="{music_id}", \\\\\n'
            f'            CuePath="{_SILENCE}", \\\\\n'
            f'            Group={group})'
        )


def _build_strategy_ini(toggles):
    """Generate XComStrategySound.ini content."""
    lines = [
        "[MusicModdingSystem.MMS_XComStrategySoundManager]",
        "; Anarchy Radio FM: Replace MMS strategy music with silence for enabled states.",
        "; Non-fallback entries always take priority over MMS defaults.",
        "; Auto-generated by Anarchy Radio FM — do not edit manually.",
        "",
    ]

    # Toggleable entries
    for toggle_key, entries in _TOGGLEABLE_STRATEGY:
        enabled = toggles.get(toggle_key, True)
        if enabled:
            for music_id, group, has_fade in entries:
                lines.append(_strategy_entry(music_id, group, has_fade))
                lines.append("")
        else:
            lines.append(f"; {toggle_key.upper()} DISABLED — MMS plays its own music.")
            for music_id, group, _ in entries:
                lines.append(f";  (skipped: {music_id} / {group})")
            lines.append("")

    # Credits — always commented out
    lines.append(";+MusicDefs=(MusicID=\"XiPod_Silence_Credits\", \\\\")
    lines.append(";            CuePath=\"XiPod_Silence.silent_Cue\", \\\\")
    lines.append(";            dontFadeIn=true, \\\\")
    lines.append(";            dontFadeOut=true, \\\\")
    lines.append(";            Group=eSSG_Credits)")
    lines.append("")

    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ #
#  Tactical config
# ------------------------------------------------------------------ #

def _build_tactical_ini(enabled):
    """Generate XComTacticalSound.ini content."""
    lines = [
        "[MusicModdingSystem.MMS_XComTacticalSoundManager]",
        "; Anarchy Radio FM: Replace MMS tactical music with silence.",
        "; Non-fallback entries always take priority.",
        "; Auto-generated by Anarchy Radio FM — do not edit manually.",
        "",
    ]
    if enabled:
        # NOTE: UE3 ini line continuation is a double backslash (\\),
        # matching the MMS reference configs. A single backslash breaks
        # the CombatDefs/ExploreDefs parse and MMS plays its own music.
        lines.append(
            f'+CombatDefs=(ID="XiPod_Silence_Combat", \\\\\n'
            f'             XLoopCue="{_SILENCE}")'
        )
        lines.append("")
        lines.append(
            f'+ExploreDefs=(ID="XiPod_Silence_Explore", \\\\\n'
            f'              Cue="{_SILENCE}")'
        )
    else:
        lines.append("; BATTLE DISABLED — MMS plays its own tactical music.")
        lines.append(f';+CombatDefs=(ID="XiPod_Silence_Combat", XLoopCue="{_SILENCE}")')
        lines.append(f';+ExploreDefs=(ID="XiPod_Silence_Explore", Cue="{_SILENCE}")')
    lines.append("")
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ #
#  Public API
# ------------------------------------------------------------------ #

def sync_ini_files(toggles, config_folder=None):
    """Rewrite all three MMS config files based on current toggle states.

    Args:
        toggles: dict mapping toggle keys to bool, e.g.
                 {"shell_menu": True, "avenger": True, "battle": False, ...}
        config_folder: path to the game's user Config directory.
                       Only needed on first call; cached after that.
    """
    global _config_dir

    if config_folder:
        _config_dir = config_folder

    if not _config_dir:
        console.warn("MMS config: no config directory set (need log_path on first call).")
        return

    if not os.path.isdir(_config_dir):
        console.warn(f"MMS config dir not found: {_config_dir}")
        return

    changes = []

    # Shell
    shell_path = os.path.join(_config_dir, "XComShellSound.ini")
    shell_content = _build_shell_ini(toggles.get("shell_menu", True))
    if _write_if_changed(shell_path, shell_content):
        changes.append("shell")

    # Strategy
    strat_path = os.path.join(_config_dir, "XComStrategySound.ini")
    strat_content = _build_strategy_ini(toggles)
    if _write_if_changed(strat_path, strat_content):
        changes.append("strategy")

    # Tactical
    tact_path = os.path.join(_config_dir, "XComTacticalSound.ini")
    tact_content = _build_tactical_ini(toggles.get("battle", True))
    if _write_if_changed(tact_path, tact_content):
        changes.append("tactical")

    if changes:
        console.signal(f"MMS config updated: {', '.join(changes)} — takes effect on next game launch.")
    else:
        console.debug("MMS config: no changes needed.")


def _write_if_changed(path, content):
    """Write file only if content differs. Returns True if written."""
    try:
        if os.path.exists(path):
            with open(path, 'r', encoding='utf-8') as f:
                existing = f.read()
            if existing == content:
                return False
    except Exception:
        pass  # If we can't read, just write

    try:
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    except Exception as e:
        console.warn(f"Failed to write {path}: {e}")
        return False
